import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Restaurant Menu Demo",
    description: "Generated by Matthew Ridgway",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme="light">
            <body className={inter.className}>
                <Header />
                <main className="flex flex-col w-full h-full p-32 items-center">
                    {children}
                </main>
            </body>
        </html>
    );
}
